#!/usr/bin/env bash
# Installs and configures HAproxy on server

sudo apt update -y
sudo apt install haproxy -y
echo "
frontend lb
    bind *:80
    mode http
    default_backend nginx-servers
    
backend nginx-servers
    mode http
    balance roundrobin
    server web-01 54.237.53.189:80 check
    server web-02 3.84.255.31:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
